In [2]:
!pip install pillow

In [1]:
!ls ..

dataset


In [13]:
from PIL import Image
import os
import numpy as np
names = []
path = 'annotations/training'
#path = 'annotations/validation'
#path = 'images/training'
#path = 'images/validation'
#path = '../ade/ADEChallengeData2016/annotations/validation'
for img in os.listdir(path):
    names.append(img)
names.sort()
print(len(names))

1280


In [8]:
from torchvision.transforms.functional import rotate
count=0
imgs=[]
for i,name in enumerate(names):
    img = Image.open(path + "/" + name)#.convert('L')
    imgs.append(np.array(img))
    rotate(img,90).save(path + "/" + name[:-4] + '_90.jpg', quality=100, subsampling=0)
    rotate(img,180).save(path + "/" + name[:-4] + '_180.jpg', quality=100, subsampling=0)
    rotate(img,270).save(path + "/" + name[:-4] + '_270.jpg', quality=100, subsampling=0)



In [9]:
print(imgs[0].shape)

(512, 512, 3)


In [10]:
print(np.std(imgs, axis=tuple(range(np.array(imgs).ndim-1))))

[40.74672974 30.74751057 20.52758501]


In [11]:
print(np.mean(imgs, axis=tuple(range(np.array(imgs).ndim-1))))
[71.186, 49.933, 36.509], std=[40.869, 31.001, 20.795]

[71.20378926 49.96402668 36.47249101]


In [15]:

mapper = {
    0:0,
    65:1,
    66:1,
    81:2,
    82:2,
    84:3,
    88:4,
    191:5,
    192:5
}
for i,name in enumerate(names):
    img = np.array(Image.open(path + "/" + name).convert('L'))
    #print(np.array(img).shape)
    #print(np.unique(np.array(img)))
    img = np.array(list(map(lambda x: list(map(mapper.get, x)),img)))
    print(np.unique(np.array(img)))
    Image.fromarray(img.astype(np.uint8)).save(path + "/" + name, quality=100, subsampling=0)
    

[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]
[0 3 4 5]


[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]


In [19]:
for i,name in enumerate(names):
    #img = np.array(Image.open(path + "/" + name).convert('L'))
    #print(np.array(img).shape)
    #print(np.unique(np.array(img)))
   
    if str(np.unique(np.array(img))) == '[0 1 2]':
        print(name)
        print(np.unique(np.array(img)))

f50v2_0.png
[0 1 2]
f50v2_0_180.png
[0 1 2]
f50v2_0_270.png
[0 1 2]
f50v2_0_90.png
[0 1 2]
f50v2_10.png
[0 1 2]
f50v2_100.png
[0 1 2]
f50v2_100_180.png
[0 1 2]
f50v2_100_270.png
[0 1 2]
f50v2_100_90.png
[0 1 2]
f50v2_101.png
[0 1 2]
f50v2_101_180.png
[0 1 2]
f50v2_101_270.png
[0 1 2]
f50v2_101_90.png
[0 1 2]
f50v2_102.png
[0 1 2]
f50v2_102_180.png
[0 1 2]
f50v2_102_270.png
[0 1 2]
f50v2_102_90.png
[0 1 2]
f50v2_103.png
[0 1 2]
f50v2_103_180.png
[0 1 2]
f50v2_103_270.png
[0 1 2]
f50v2_103_90.png
[0 1 2]
f50v2_104.png
[0 1 2]
f50v2_104_180.png
[0 1 2]
f50v2_104_270.png
[0 1 2]
f50v2_104_90.png
[0 1 2]
f50v2_105.png
[0 1 2]
f50v2_105_180.png
[0 1 2]
f50v2_105_270.png
[0 1 2]
f50v2_105_90.png
[0 1 2]
f50v2_106.png
[0 1 2]
f50v2_106_180.png
[0 1 2]
f50v2_106_270.png
[0 1 2]
f50v2_106_90.png
[0 1 2]
f50v2_108.png
[0 1 2]
f50v2_108_180.png
[0 1 2]
f50v2_108_270.png
[0 1 2]
f50v2_108_90.png
[0 1 2]
f50v2_109.png
[0 1 2]
f50v2_109_180.png
[0 1 2]
f50v2_109_270.png
[0 1 2]
f50v2_109_90.png
[0 1 

f50v2_198.png
[0 1 2]
f50v2_198_180.png
[0 1 2]
f50v2_198_270.png
[0 1 2]
f50v2_198_90.png
[0 1 2]
f50v2_199.png
[0 1 2]
f50v2_199_180.png
[0 1 2]
f50v2_199_270.png
[0 1 2]
f50v2_199_90.png
[0 1 2]
f50v2_19_180.png
[0 1 2]
f50v2_19_270.png
[0 1 2]
f50v2_19_90.png
[0 1 2]
f50v2_2.png
[0 1 2]
f50v2_20.png
[0 1 2]
f50v2_200.png
[0 1 2]
f50v2_200_180.png
[0 1 2]
f50v2_200_270.png
[0 1 2]
f50v2_200_90.png
[0 1 2]
f50v2_201.png
[0 1 2]
f50v2_201_180.png
[0 1 2]
f50v2_201_270.png
[0 1 2]
f50v2_201_90.png
[0 1 2]
f50v2_202.png
[0 1 2]
f50v2_202_180.png
[0 1 2]
f50v2_202_270.png
[0 1 2]
f50v2_202_90.png
[0 1 2]
f50v2_203.png
[0 1 2]
f50v2_203_180.png
[0 1 2]
f50v2_203_270.png
[0 1 2]
f50v2_203_90.png
[0 1 2]
f50v2_204.png
[0 1 2]
f50v2_204_180.png
[0 1 2]
f50v2_204_270.png
[0 1 2]
f50v2_204_90.png
[0 1 2]
f50v2_205.png
[0 1 2]
f50v2_205_180.png
[0 1 2]
f50v2_205_270.png
[0 1 2]
f50v2_205_90.png
[0 1 2]
f50v2_206.png
[0 1 2]
f50v2_206_180.png
[0 1 2]
f50v2_206_270.png
[0 1 2]
f50v2_206_90.png
[0

[0 1 2]
f73new_114.png
[0 1 2]
f73new_114_180.png
[0 1 2]
f73new_114_270.png
[0 1 2]
f73new_114_90.png
[0 1 2]
f73new_115.png
[0 1 2]
f73new_115_180.png
[0 1 2]
f73new_115_270.png
[0 1 2]
f73new_115_90.png
[0 1 2]
f73new_117.png
[0 1 2]
f73new_117_180.png
[0 1 2]
f73new_117_270.png
[0 1 2]
f73new_117_90.png
[0 1 2]
f73new_118.png
[0 1 2]
f73new_118_180.png
[0 1 2]
f73new_118_270.png
[0 1 2]
f73new_118_90.png
[0 1 2]
f73new_119.png
[0 1 2]
f73new_119_180.png
[0 1 2]
f73new_119_270.png
[0 1 2]
f73new_119_90.png
[0 1 2]
f73new_12.png
[0 1 2]
f73new_120.png
[0 1 2]
f73new_120_180.png
[0 1 2]
f73new_120_270.png
[0 1 2]
f73new_120_90.png
[0 1 2]
f73new_121.png
[0 1 2]
f73new_121_180.png
[0 1 2]
f73new_121_270.png
[0 1 2]
f73new_121_90.png
[0 1 2]
f73new_122.png
[0 1 2]
f73new_122_180.png
[0 1 2]
f73new_122_270.png
[0 1 2]
f73new_122_90.png
[0 1 2]
f73new_123.png
[0 1 2]
f73new_123_180.png
[0 1 2]
f73new_123_270.png
[0 1 2]
f73new_123_90.png
[0 1 2]
f73new_125.png
[0 1 2]
f73new_125_180.png
[

f73new_36.png
[0 1 2]
f73new_36_180.png
[0 1 2]
f73new_36_270.png
[0 1 2]
f73new_36_90.png
[0 1 2]
f73new_37.png
[0 1 2]
f73new_37_180.png
[0 1 2]
f73new_37_270.png
[0 1 2]
f73new_37_90.png
[0 1 2]
f73new_38.png
[0 1 2]
f73new_38_180.png
[0 1 2]
f73new_38_270.png
[0 1 2]
f73new_38_90.png
[0 1 2]
f73new_39.png
[0 1 2]
f73new_39_180.png
[0 1 2]
f73new_39_270.png
[0 1 2]
f73new_39_90.png
[0 1 2]
f73new_3_180.png
[0 1 2]
f73new_3_270.png
[0 1 2]
f73new_3_90.png
[0 1 2]
f73new_4.png
[0 1 2]
f73new_41.png
[0 1 2]
f73new_41_180.png
[0 1 2]
f73new_41_270.png
[0 1 2]
f73new_41_90.png
[0 1 2]
f73new_42.png
[0 1 2]
f73new_42_180.png
[0 1 2]
f73new_42_270.png
[0 1 2]
f73new_42_90.png
[0 1 2]
f73new_43.png
[0 1 2]
f73new_43_180.png
[0 1 2]
f73new_43_270.png
[0 1 2]
f73new_43_90.png
[0 1 2]
f73new_44.png
[0 1 2]
f73new_44_180.png
[0 1 2]
f73new_44_270.png
[0 1 2]
f73new_44_90.png
[0 1 2]
f73new_45.png
[0 1 2]
f73new_45_180.png
[0 1 2]
f73new_45_270.png
[0 1 2]
f73new_45_90.png
[0 1 2]
f73new_46.png


KeyboardInterrupt: 